version: '3.8'

networks:
  stretch_team:
    name: stretch_team
    driver: bridge

services:
  # Database - PostgreSQL
  postgres-db:
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--data-checksums"
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    networks:
      - stretch_team
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: