version: '3.8'

networks:
  stretch_team:
    name: stretch_team
    driver: bridge

services:
  # Database - PostgreSQL
  postgres-db:
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS="--data-checksums"
    build:
      context: ./database
      dockerfile: Dockerfile
    image: database
    networks:
      - stretch_team
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # Market - Django
  django-market:
    container_name: market
    build:
      context: ./market
      dockerfile: Dockerfile
    image: market
    networks:
      - stretch_team
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    volumes:
      - ./market:/app

volumes:
  postgres_data:
