[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["jhonata"]
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.2"
fastapi = "^0.115.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
